'use client';

import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { AnimatePresence, motion, useMotionValue, useReducedMotion, useSpring } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, Code2, Copy, Download, Github, Linkedin, Mail, Menu, Moon, Send, Sun, TerminalSquare, X } from 'lucide-react';

const stack = [
  ['React', 'Interface systems', 'Composing product-grade UI with deliberate state and motion.'], ['Next.js', 'Web products', 'Fast, search-friendly applications with modern routing.'], ['TypeScript', 'Reliable scale', 'Type-safe contracts that keep teams moving quickly.'], ['JavaScript', 'Core craft', 'The flexible layer underneath every polished interaction.'], ['Node.js', 'Product APIs', 'Eventful server-side systems that meet frontend needs.'], ['NestJS', 'Backend architecture', 'Structured services designed to grow without friction.'], ['Spring Boot', 'Enterprise systems', 'Reliable Java services and production integrations.'], ['PostgreSQL', 'Data integrity', 'Thoughtful relational modelling and query performance.'], ['MongoDB', 'Flexible data', 'Document models for fast-moving product requirements.'], ['Firebase', 'Rapid shipping', 'Authentication, realtime data and streamlined deployment.'], ['AWS', 'Cloud delivery', 'Pragmatic cloud infrastructure and release workflows.'], ['Docker', 'Reproducible builds', 'Same environment from local development to production.'], ['Tailwind CSS', 'Design velocity', 'Consistent interfaces without CSS drift.'], ['Material UI', 'Product foundations', 'Accessible primitives shaped into bespoke experiences.'], ['Redux', 'State clarity', 'Predictable app state for complex user flows.'], ['GraphQL', 'Connected data', 'Precise client data requirements with scalable APIs.'], ['Git', 'Team flow', 'Versioned collaboration and confident iteration.'],
];

const projects = [
  { slug: 'teamtrakr', number: '01', title: 'TeamTrakr', eyebrow: 'SaaS workforce management', description: 'A multi-tenant workspace for projects, attendance, employee engagement, subscription management and team administration.', role: 'React developer', tech: ['React', 'TypeScript', 'Tailwind CSS', 'REST APIs'], features: ['Task and attendance workflows', 'RBAC user management', 'Subscription experiences'], accent: 'lime', architecture: 'Reusable React and TypeScript components communicate with REST APIs, with role-aware dashboards and state built for live workspace updates.', problem: 'Modern teams needed a unified workspace that supports productivity, engagement and operational oversight.', result: 'A responsive SaaS experience covering project summaries, attendance widgets, management tools and subscription flows.' },
  { slug: 'teamrex', number: '02', title: 'Teamrex', eyebrow: 'SaaS collaboration platform', description: 'A real-time collaboration workspace for chat, video meetings, file sharing, team channels and notifications.', role: 'React developer', tech: ['React', 'Next.js', 'Bootstrap', 'WebSockets'], features: ['Instant chat', 'Channel management', 'File sharing'], accent: 'violet', architecture: 'React and Next.js interfaces use REST APIs and WebSockets to surface live messaging, presence and channel activity.', problem: 'Teams required reliable communication, shared files and channel coordination within a single subscription platform.', result: 'A responsive collaboration experience with real-time updates, role-aware screens and subscription UI flows.' },
  { slug: 'jobber', number: '03', title: 'Jobber', eyebrow: 'Recruitment module', description: 'A recruitment platform for tracking resumes, candidate profiles and application status in one organized workflow.', role: 'React developer', tech: ['React', 'Next.js', 'Redux Toolkit', 'Swagger'], features: ['Resume upload', 'Candidate status tracking', 'Profile management'], accent: 'blue', architecture: 'A modular React UI uses Redux Toolkit for shared state and Swagger-documented APIs for consistent recruitment data flows.', problem: 'Recruiters needed a clearer way to manage candidate records and application progress.', result: 'A maintainable recruitment module with reusable components and real-time-feeling UI updates.' },
  { slug: 'timespace', number: '04', title: 'Time & Space', eyebrow: 'Metro advertising inventory', description: 'An interactive web platform that presents Hyderabad Metro advertising inventory across stations and pillars.', role: 'React frontend developer', tech: ['React', 'Material UI', 'REST APIs'], features: ['Location-based browsing', 'Media showcases', 'Responsive inventory views'], accent: 'blue', architecture: 'A responsive React interface uses Material UI components to make location-specific media inventory easy to browse.', problem: 'Businesses and agencies needed a polished way to discover outdoor branding opportunities by location.', result: 'A modern, scalable showcase that turns advertising inventory into an accessible digital catalogue.' },
  { slug: 'zenn', number: '05', title: 'Zenn', eyebrow: 'Catering & product ordering', description: 'An Australia-based catering and product ordering website with a smooth journey from menu browsing to order placement.', role: 'Next.js frontend developer', tech: ['Next.js', 'Material UI', 'REST APIs'], features: ['Dynamic menus', 'Cart management', 'Order placement'], accent: 'orange', architecture: 'Next.js pages and reusable Material UI components consume live product and order data through REST APIs.', problem: 'The client needed a clear ordering experience that worked beautifully on desktop, tablet and mobile.', result: 'A responsive commerce experience for catering menus, products and real-time ordering data.' },
  { slug: 'stdreux', number: '06', title: 'St Dreux', eyebrow: 'Catering operations', description: 'An Australia-based catering and ordering management platform for browsing menus, managing addresses and tracking orders.', role: 'Next.js frontend developer', tech: ['Next.js', 'Material UI', 'REST APIs'], features: ['Order history', 'Address management', 'Customer workflows'], accent: 'orange', architecture: 'Reusable frontend modules communicate with REST APIs for product data, user profiles and order processing.', problem: 'Customers and operations teams needed a more intuitive end-to-end ordering and management flow.', result: 'A scalable, cross-browser ordering experience designed for the full customer journey.' },
];

const terminalResponses: Record<string, string[]> = {
  whoami: ['Sandeep Bhargav', 'Frontend Developer', 'React • Next.js • TypeScript'],
  about: ['2.1 years building responsive, interactive and scalable React applications.', 'I turn complex requirements into clear product experiences.'],
  skills: ['React, Next.js, TypeScript, JavaScript, HTML5, CSS3, Material UI and Bootstrap.', 'REST API integration with Axios and Fetch API.'],
  projects: ['TeamTrakr · Teamrex · Jobber · Time & Space · Zenn · St Dreux', 'Scroll up for selected work.'],
  experience: ['Frontend Developer at TResource Innovations Pvt Ltd (part of Ekipit).', 'July 2024 to present.'],
  contact: ['Open to meaningful product challenges.', 'sandeepbhargavmurarishetti@gmail.com'],
};

const reveal = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.18 }, transition: { duration: 0.65, ease: [0.16, 1, 0.3, 1] } } as const;

function Magnetic({ children, className = '', onClick }: { children: React.ReactNode; className?: string; onClick?: () => void }) {
  const x = useMotionValue(0); const y = useMotionValue(0); const sx = useSpring(x, { stiffness: 220, damping: 16 }); const sy = useSpring(y, { stiffness: 220, damping: 16 });
  return <motion.button onClick={onClick} onMouseMove={(e) => { const b = e.currentTarget.getBoundingClientRect(); x.set((e.clientX - b.left - b.width / 2) * .16); y.set((e.clientY - b.top - b.height / 2) * .16); }} onMouseLeave={() => { x.set(0); y.set(0); }} style={{ x: sx, y: sy }} className={className}>{children}</motion.button>;
}

function Cursor() { const x = useMotionValue(-50); const y = useMotionValue(-50); const sx = useSpring(x, { stiffness: 700, damping: 35 }); const sy = useSpring(y, { stiffness: 700, damping: 35 }); const [mode, setMode] = useState(''); useEffect(() => { const move = (e: MouseEvent) => { x.set(e.clientX); y.set(e.clientY); const t = e.target as HTMLElement; setMode(t.closest('[data-cursor]')?.getAttribute('data-cursor') || ''); }; window.addEventListener('mousemove', move); return () => window.removeEventListener('mousemove', move); }, [x, y]); return <motion.div className={`cursor ${mode}`} style={{ x: sx, y: sy }}>{mode === 'view' && <span>VIEW</span>}</motion.div>; }

function Navbar({ light, setLight }: { light: boolean; setLight: (v: boolean) => void }) { const [open, setOpen] = useState(false); const links = ['Home', 'About', 'Skills', 'Projects', 'Experience', 'Contact']; return <header className="nav-wrap"><nav className="nav" aria-label="Main navigation"><a className="brand" href="#home">SANDEEP<span>.DEV</span></a><div className="nav-links">{links.map(l => <a key={l} href={`#${l.toLowerCase()}`}>{l}</a>)}</div><div className="nav-actions"><button aria-label="Toggle color theme" className="icon-button" onClick={() => setLight(!light)}>{light ? <Moon size={16} /> : <Sun size={16} />}</button><a className="resume" href="#contact"><Download size={14} /> Resume</a><button aria-label="Open menu" className="icon-button mobile-menu" onClick={() => setOpen(!open)}>{open ? <X size={18} /> : <Menu size={18} />}</button></div></nav><AnimatePresence>{open && <motion.div className="mobile-nav" initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}>{links.map(l => <a key={l} onClick={() => setOpen(false)} href={`#${l.toLowerCase()}`}>{l}</a>)}</motion.div>}</AnimatePresence></header> }

function CodePanel() { return <div className="workspace-wrap"><div className="workspace"><div className="editor-top"><div className="dots"><i /><i /><i /></div><span>sandeep.ts</span><Code2 size={15} /></div><pre><code><span className="purple">const</span> <span className="blue">developer</span> = {'{'}{`\n`}  <span className="aqua">name</span>: <span className="yellow">&quot;Sandeep&quot;</span>,{`\n`}  <span className="aqua">stack</span>: [<span className="yellow">&quot;React&quot;</span>, <span className="yellow">&quot;Next.js&quot;</span>, <span className="yellow">&quot;Node.js&quot;</span>],{`\n`}  <span className="aqua">passion</span>: <span className="yellow">&quot;Building products&quot;</span>,{`\n`}  <span className="aqua">approach</span>: <span className="yellow">&quot;Intentional&quot;</span>{`\n`}{'}'};</code></pre><div className="editor-status"><span><b /> system online</span><span>TypeScript</span></div></div><motion.div className="terminal-float" animate={{ y: [0, -8, 0] }} transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}><div className="float-title"><TerminalSquare size={13} /> terminal <span>•••</span></div><p>$ npm run build</p><p className="muted">$ deploying...</p><p className="success">$ success <Check size={12} /></p></motion.div><div className="orbit orbit-one" /><div className="orbit orbit-two" /></div> }

function Hero() { return <section id="home" className="hero section"><div className="hero-copy"><motion.div className="availability" {...reveal}><span /> Available for opportunities</motion.div><motion.h1 initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .75, ease: [0.16, 1, 0.3, 1] }}>Building Digital<br />Products That <em>Actually</em> Work.</motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .35, duration: .7 }}>I&apos;m Sandeep Bhargav — a React-focused developer who turns complex ideas into fast, scalable and intuitive web experiences.</motion.p><motion.div className="hero-ctas" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .5 }}><Magnetic className="button primary" onClick={() => document.querySelector('#projects')?.scrollIntoView({ behavior: 'smooth' })}>View My Work <ArrowDownRight size={17} /></Magnetic><Magnetic className="button ghost" onClick={() => document.querySelector('#contact')?.scrollIntoView({ behavior: 'smooth' })}>Let&apos;s Work Together <ArrowUpRight size={17} /></Magnetic></motion.div></div><motion.div className="hero-visual portrait-wrap" initial={{ opacity: 0, scale: .94, rotate: 2 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ duration: .9, delay: .15, ease: [0.16, 1, 0.3, 1] }}><motion.div className="portrait-orbit" animate={{ rotate: 360 }} transition={{ duration: 24, repeat: Infinity, ease: 'linear' }}><i /></motion.div><motion.div className="portrait-card" whileHover={{ y: -8, rotate: -1 }} transition={{ type: 'spring', stiffness: 210, damping: 20 }}><Image src="/images/sandeep-portrait.png" alt="Sandeep Bhargav, Frontend Developer" fill priority sizes="(max-width: 850px) 90vw, 480px" /><motion.i className="portrait-scan" animate={{ y: ['-120%', '680%'] }} transition={{ duration: 5, repeat: Infinity, repeatDelay: 2, ease: 'easeInOut' }} /></motion.div><motion.div className="portrait-label" animate={{ y: [0, -6, 0] }} transition={{ duration: 4.5, repeat: Infinity, ease: 'easeInOut' }}><span>Frontend Developer</span><strong>Sandeep<br />Bhargav</strong><i>React · Next.js · TypeScript</i></motion.div><motion.div className="portrait-status" animate={{ y: [0, 7, 0] }} transition={{ duration: 3.8, repeat: Infinity, ease: 'easeInOut' }}><span><i /> OPEN TO COLLABORATE</span><strong>2.1 years of<br />product craft</strong></motion.div></motion.div><a className="scroll-cue" href="#about"><span /> Scroll to explore</a></section> }

function Intro() { const items = ['Frontend development', 'API integration', 'Responsive UI', 'Real-time interfaces', 'Performance optimization', 'Design systems', 'Problem solving']; return <section id="about" className="section intro"><motion.div className="section-label" {...reveal}>01 / Behind the code</motion.div><motion.h2 {...reveal}>I don&apos;t just write code.<br /><span>I build experiences.</span></motion.h2><div className="intro-grid"><motion.p {...reveal}>With 2.1 years of frontend experience, I turn wireframes and product requirements into responsive, reliable React experiences — with attention to performance, clarity and the details users notice.</motion.p><motion.div className="capabilities" {...reveal}>{items.map((item, i) => <div key={item}><span>0{i + 1}</span>{item}<ArrowUpRight size={16} /></div>)}</motion.div></div><div className="metric-row">{[['2.1', 'Years experience'], ['6', 'Projects featured'], ['11+', 'Core tools'], ['100%', 'Passion for building']].map(([n, l]) => <motion.div key={l} {...reveal}><strong>{n}</strong><span>{l}</span></motion.div>)}</div></section> }

function TechStack() { const [active, setActive] = useState(0); return <section id="skills" className="section tech-section"><motion.div className="section-label" {...reveal}>02 / Technology ecosystem</motion.div><motion.div className="tech-head" {...reveal}><h2>A flexible stack<br />for <span>real products.</span></h2><p>Tools are only valuable when they help you build the right thing. Here&apos;s what I reach for and why.</p></motion.div><div className="stack-stage"><div className="stack-center"><small>THE SYSTEM</small><strong>MY<br />STACK</strong><span>17 tools</span></div>{stack.map(([name, use], i) => <button key={name} onMouseEnter={() => setActive(i)} onFocus={() => setActive(i)} className={`tech-node node-${i + 1} ${active === i ? 'active' : ''}`}><span>{name}</span><small>{use}</small></button>)}<motion.div className="stack-detail" key={stack[active][0]} initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }}><b>{stack[active][0]}</b><span>{stack[active][1]}</span><p>{stack[active][2]}</p></motion.div></div><div className="tech-mobile-list">{stack.map(([name, use]) => <div key={name}><strong>{name}</strong><span>{use}</span></div>)}</div></section> }

function ProjectPreview({ project }: { project: typeof projects[number] }) {
  const content = {
    teamtrakr: <><div className="preview-side"><b>T</b><i /><i /><i /><i /></div><div className="dashboard"><span>Good morning, Sandeep</span><strong>Today&apos;s overview</strong><div className="dash-grid"><div><small>Present</small><b>142</b><em>+8.2%</em></div><div><small>On leave</small><b>12</b><em>+1.4%</em></div></div><div className="chart"><i /><i /><i /><i /><i /><i /><i /></div></div></>,
    teamrex: <><div className="event-orb" /><div className="event-copy"><small>TEAM COMMUNICATION</small><strong>Work<br />better <i>together.</i></strong><span className="preview-action">Open workspace</span></div><div className="event-date">24<br /><small>LIVE</small></div></>,
    jobber: <><div className="hire-head"><b>jobber</b><span>Find candidates</span><span>For recruiters</span></div><div className="hire-main"><small>FIND THE RIGHT</small><strong>People make<br />progress.</strong><div>Search candidates, status or skill <b>→</b></div></div></>,
    zenn: <><div className="plate-head"><b>zenn<span>{'&'}</span>catering</b><span>MENU · CART · ORDER</span></div><div className="plate-main"><small>FRESH / CATERING</small><strong>Good food,<br />made simple.</strong><div className="food-disc" /></div></>,
  } as Record<string, React.ReactNode>;
  const fallback = <div className="event-copy"><small>DIGITAL PLATFORM</small><strong>{project.title}<br /><i>made clear.</i></strong><span className="preview-action">Explore experience</span></div>;
  return <div className={`preview ${project.accent}`}><div className="preview-nav"><i /><span>{project.title.toUpperCase()}</span><b>•••</b></div><div className="preview-body">{content[project.slug] || fallback}</div></div>;
}

function Projects({ onSelect }: { onSelect: (p: typeof projects[number]) => void }) { return <section id="projects" className="section projects"><motion.div className="projects-top" {...reveal}><div><div className="section-label">03 / Selected work</div><h2>Built for <span>the real world.</span></h2></div><p>Selected platforms where product thinking, interface craft and technical detail come together.</p></motion.div><div className="project-list">{projects.map((p, i) => <motion.article key={p.slug} className="project" {...reveal}><button data-cursor="view" className="project-visual" onClick={() => onSelect(p)}><ProjectPreview project={p} /><span className="view-project">View case study <ArrowUpRight size={17} /></span></button><div className="project-info"><span className="project-number">{p.number}</span><div><p className="eyebrow">{p.eyebrow}</p><h3>{p.title}</h3><p className="project-desc">{p.description}</p><div className="tags">{p.tech.map(t => <span key={t}>{t}</span>)}</div><button className="text-link" onClick={() => onSelect(p)}>Explore project <ArrowUpRight size={15} /></button></div></div></motion.article>)}</div><Magnetic className="all-projects">View all projects <ArrowDownRight size={16} /></Magnetic></section> }

function Experience() { const items = [{ year: '2024', title: 'TResource Innovations Pvt Ltd', role: 'Frontend Developer · July 2024 to present', body: 'Building scalable SaaS interfaces for TeamTrakr and Teamrex, from responsive dashboards and component systems to API integration and real-time collaboration surfaces.', tags: ['React', 'Next.js', 'TypeScript', 'REST APIs'] }, { year: '2025', title: 'Client product delivery', role: 'React / Next.js developer', body: 'Delivered recruitment, metro advertising and Australian catering experiences with reusable UI components, responsive workflows and practical API integrations.', tags: ['Redux Toolkit', 'Material UI', 'Bootstrap', 'WebSockets'] }, { year: '2026', title: 'Continuing to build', role: 'Product-minded frontend engineer', body: 'Focused on refining reliable frontend systems, improving performance and translating complex requirements into clear user experiences.', tags: ['React', 'Next.js', 'Git', 'Postman'] }]; return <section id="experience" className="section experience"><motion.div className="section-label" {...reveal}>04 / The journey</motion.div><motion.h2 {...reveal}>A record of<br /><span>making progress.</span></motion.h2><div className="timeline">{items.map((item, i) => <motion.article key={item.year} {...reveal}><div className="time-year">{item.year}<i /></div><div className="time-content"><p className="eyebrow">{item.role}</p><h3>{item.title}</h3><p>{item.body}</p><div className="tags">{item.tags.map(t => <span key={t}>{t}</span>)}</div></div><span className="time-index">0{i + 1}</span></motion.article>)}</div></section> }

function Process() { const steps = [['01', 'Understand', 'Listen deeply, frame the actual problem, and identify the outcome worth pursuing.'], ['02', 'Plan', 'Turn uncertainty into a clear execution path before momentum creates expensive rework.'], ['03', 'Design', 'Shape interfaces around people, decisions, and the moments that genuinely matter.'], ['04', 'Build', 'Ship careful, scalable code with performance and accessibility built into the work.'], ['05', 'Launch', 'Test, release, learn — then keep improving what the product needs next.']]; const [active, setActive] = useState(0); return <section className="section process"><motion.div className="section-label" {...reveal}>05 / How I build</motion.div><motion.div className="process-intro" {...reveal}><h2>Clear thinking.<br /><span>Confident shipping.</span></h2><p>Every useful product follows a rhythm. This is mine.</p></motion.div><div className="process-list">{steps.map(([number, title, body], i) => <button className={active === i ? 'selected' : ''} onClick={() => setActive(i)} key={title}><span>{number}</span><strong>{title}</strong><div>{body}</div><ChevronRight size={18} /></button>)}</div></section> }

function Activity() { return <section className="section activity"><motion.div className="activity-card" {...reveal}><div className="activity-top"><div><div className="section-label">06 / Builder&apos;s log</div><h2>Steady craft,<br /><span>visible progress.</span></h2></div><div className="live-dot"><i /> active</div></div><div className="activity-grid"><div className="contributions"><div className="contribution-head"><span>Contribution rhythm</span><small>Designed snapshot · not live GitHub data</small></div><div className="heatmap">{Array.from({ length: 84 }, (_, i) => <i key={i} className={`l${(i * 7 + i % 5) % 5}`} />)}</div><div className="heat-legend">Less <i className="l0" /><i className="l1" /><i className="l2" /><i className="l3" /><i className="l4" /> More</div></div><div className="activity-stats"><div><strong>6</strong><small>featured products</small></div><div><strong>2.1</strong><small>years experience</small></div><div><strong>4</strong><small>domains explored</small></div></div></div></motion.div></section> }

function InteractiveTerminal() { const [command, setCommand] = useState('whoami'); const [copied, setCopied] = useState(false); const output = terminalResponses[command]; return <section className="section terminal-section"><motion.div className="terminal-shell" {...reveal}><div className="terminal-bar"><div className="dots"><i /><i /><i /></div><span><TerminalSquare size={14} /> sandeep@portfolio:~</span><button aria-label="Copy terminal output" onClick={() => { navigator.clipboard?.writeText(output.join('\n')); setCopied(true); setTimeout(() => setCopied(false), 1200); }}>{copied ? <Check size={14} /> : <Copy size={14} />}</button></div><div className="terminal-content"><div><span className="prompt">$</span> whoami</div><AnimatePresence mode="wait"><motion.div key={command} className="terminal-output" initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: .22 }}>{output.map(line => <p key={line}>{line}</p>)}</motion.div></AnimatePresence><div className="terminal-command"><span className="prompt">$</span><span>choose a command</span><i /></div><div className="terminal-commands">{Object.keys(terminalResponses).map(c => <button key={c} className={c === command ? 'active' : ''} onClick={() => setCommand(c)}>{c}</button>)}</div></div></motion.div></section> }

function Contact() { const [form, setForm] = useState({ name: '', email: '', type: '', message: '' }); const [state, setState] = useState<'idle' | 'loading' | 'success' | 'error'>('idle'); const [errors, setErrors] = useState<Record<string, string>>({}); const submit = (e: React.FormEvent) => { e.preventDefault(); const next: Record<string, string> = {}; if (!form.name.trim()) next.name = 'Please add your name.'; if (!/^\S+@\S+\.\S+$/.test(form.email)) next.email = 'Enter a valid email address.'; if (!form.type) next.type = 'Choose a project type.'; if (form.message.trim().length < 12) next.message = 'Tell me a little more (12 characters minimum).'; setErrors(next); if (Object.keys(next).length) { setState('error'); return; } setState('loading'); setTimeout(() => setState('success'), 1150); }; return <section id="contact" className="section contact"><motion.div className="contact-copy" {...reveal}><div className="section-label">07 / Start something</div><h2>Have an idea?<br /><span>Let&apos;s build it.</span></h2><p>Whether you&apos;re building a product, improving an existing application, or solving a complex technical problem, let&apos;s create something meaningful.</p><div className="contact-links"><a href="mailto:sandeepbhargavmurarishetti@gmail.com"><Mail size={16} /> sandeepbhargavmurarishetti@gmail.com <ArrowUpRight size={14} /></a></div></motion.div><motion.form onSubmit={submit} noValidate {...reveal}><div className="form-row"><label>Name<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name" />{errors.name && <small>{errors.name}</small>}</label><label>Email<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@company.com" />{errors.email && <small>{errors.email}</small>}</label></div><label>Project type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="">Select a project type</option><option>New product</option><option>Existing product improvement</option><option>Frontend development</option><option>Full-stack development</option><option>Something else</option></select>{errors.type && <small>{errors.type}</small>}</label><label>Tell me about it<textarea value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="A little context goes a long way..." rows={4} />{errors.message && <small>{errors.message}</small>}</label><button className="button primary submit" disabled={state === 'loading'}>{state === 'loading' ? 'Sending...' : state === 'success' ? 'Message ready — thank you' : 'Start a conversation'} <Send size={15} /></button>{state === 'success' && <p className="form-success"><Check size={14} /> Your message is ready to send. I&apos;ll be in touch soon.</p>}</motion.form></section> }

function CaseStudy({ project, close }: { project: typeof projects[number] | null; close: () => void }) { useEffect(() => { const key = (e: KeyboardEvent) => e.key === 'Escape' && close(); window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [close]); return <AnimatePresence>{project && <motion.div className="modal-layer" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} role="dialog" aria-modal="true" aria-label={`${project.title} case study`} onMouseDown={close}><motion.article className="case-study" initial={{ y: 30, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 30, opacity: 0 }} onMouseDown={e => e.stopPropagation()}><button className="case-close" onClick={close} aria-label="Close case study"><X size={20} /></button><p className="eyebrow">CASE STUDY / {project.number}</p><h2>{project.title}</h2><ProjectPreview project={project} /><div className="case-grid"><div><small>THE PROBLEM</small><p>{project.problem}</p></div><div><small>THE SOLUTION</small><p>{project.description}</p></div><div><small>ARCHITECTURE</small><p>{project.architecture}</p></div><div><small>RESULT</small><p>{project.result}</p></div></div><div className="case-footer"><div className="tags">{project.tech.map(t => <span key={t}>{t}</span>)}</div><button className="button primary" onClick={close}>Back to work <ArrowDownRight size={16} /></button></div></motion.article></motion.div>}</AnimatePresence> }

function Footer() { return <footer><a className="brand" href="#home">SANDEEP<span>.DEV</span></a><p>Designed & engineered with intention.</p><span>© {new Date().getFullYear()} Sandeep Bhargav</span></footer> }

export default function Home() { const [light, setLight] = useState(false); const [selected, setSelected] = useState<typeof projects[number] | null>(null); const [hydrated, setHydrated] = useState(false); const reduce = useReducedMotion(); useEffect(() => { setHydrated(true); }, []); useEffect(() => { document.documentElement.dataset.theme = light ? 'light' : 'dark'; }, [light]); return <main className={hydrated && reduce ? 'reduce-motion' : ''}><Cursor /><Navbar light={light} setLight={setLight} /><Hero /><Intro /><TechStack /><Projects onSelect={setSelected} /><Experience /><Process /><Activity /><InteractiveTerminal /><Contact /><Footer /><CaseStudy project={selected} close={() => setSelected(null)} /></main> }
